---
title: "Reflection on Regression and Classification Models with Group Project Data"
subtitle: "Analytics Objective - Group 2, RO4: Profit Impact of Customer Retention"
author: "Leeann Lewis-Waddell"
date: today
format:
  html:
    toc: true
    toc-depth: 4
    toc-expand: 1
    toc-location: right-body
    toc-title: "Contents"
    number-sections: true
    code-fold: show
    code-tools: true
    theme: cosmo
    highlight-style: github
    df-print: kable
    embed-resources: true
execute:
  warning: false
  message: false
  freeze: true
---

# Dataset

[Shopify Sales Dataset for ML & EDA](https://www.kaggle.com/datasets/aliiihussain/shopify-sales-dataset-for-ml-and-eda/data)

# Analytics Objectives

## State your AO  for your project.

### Original AO: 

Determine whether repeat customers are a more margin-efficient growth channel than new customer acquisition

-   **The Hypothesis:** Repeat customers are a more margin-efficient growth channel than new customer acquisition, generating higher cumulative profit and lower return rates than one-time customers, and are disproportionately acquired through lower-cost channels (Organic, Direct, Email) rather than paid channels (Paid Ads, Social Media).

### Revised AO:

Develop a supervised classification model that uses a customer’s acquisition channel and initial transaction characteristics to predict if customers will make repeat purchases within a time span of 90 days, identifying which customer segments have the greatest potential for profitable retention.

> If your AO didn't involve machine learning (supervised or unsupervised learning), please revise it so that the objective is appropriately stated for a machine learning task. Further state how you will address the objectives. Specifically describe the following:

1.  Supervised learning or unsupervised learning

    -   RO4 will use [**supervised learning**]{.underline} because the model will be trained using a defined outcome variable indicating whether each customer made a repeat purchase within 90 days of their initial transaction.

2.  What are the variables to be included and their roles (i.e., outcome vs. features)

    | Variable | Role | Data Type | Reasoning |
    |-----------------|----------|------------|----------------------------------|
    | `repeat_90_days` | Outcome | Binary categorical | Indicates whether the customer made another purchase within 90 days of the initial transaction. |
    | Traffic source | Feature | Categorical | Examines whether the customer’s acquisition channel helps predict repeat purchasing. |
    | Product category | Feature | Categorical | Accounts for differences in repeat-purchase behavior across product types. |
    | Initial order revenue | Feature | Numeric | Represents the total value of the customer’s initial purchase. |
    | Discount percentage | Feature | Numeric | Examines whether the discount applied to the initial purchase helps predict whether the customer will return. |

    ::: callout-note
    `Customer ID` and `Order ID` will be used to organize transactions and construct the `repeat_90_days` outcome variable, but they will not be included as predictive features.
    :::

3.  Name of the broader category of machine learning methods (i.e., regression vs. classification)

    -   The broader machine learning method will be [**binary classification**]{.underline} because the model will predict one of two outcomes: whether a customer will or will not make a repeat purchase within 90 days.

# Codebooks

> Choose either of the two codebooks that explain methods for your chosen machine learning task (i.e., regression vs. classification)

-   [https://jaejungca.github.io/regression-models/m04_regression_models.htmlLinks to an external site.](https://jaejungca.github.io/regression-models/m04_regression_models.html)

-   [https://jaejungca.github.io/classification/m05_classification_clustering.html#na%C3%AFve-bayes-classifierLinks to an external site.](https://jaejungca.github.io/classification/m05_classification_clustering.html#na%C3%AFve-bayes-classifier) 

This project will use the [**classification**]{.underline}codebook because `repeat_90_days` is a binary outcome. The model will predict whether a customer will make another purchase within 90 days or not.

The classification methods in the codebook will be compared to determine which model performs best at predicting repeat customers.

# Libraries

> Set up your QMD file with appropriate libraries and data and go through the entire machine learning process for your AO according to the process explained in the codebook.

1.  First, pick a machine learning method and explain why the method would be the best.  

2.  Second, go through the entire machine learning process for your AO according to the process explained in the codebook. The process will include data splitting, recipe creation, model specification, model fitting, and model evaluation. Interpret the results.

3.  What alternative methods can you try to improve the metrics produced above? Try them.

4.  Compare all methods you tried using 10-fold cross-validation. Interpret the results. Which one is the best? Does it make sense? Why or why not?

5.  Produce a chart that shows the importance of features. Is the result reasonable? Why or why not? 

# Module 5 Questions

> Address the five questions at the end of either Module 4 (Regression) or Module 5 (Classification) codebook, depending on your AO.

# Appendix

-   [GitHub Repo](https://github.com/lewiswaddell/M08.git)

-   [GitHub Pages](https://lewiswaddell.github.io/M08/)
